export const TIMING = {
  // BPM Limits
  BPM_MIN: 60,
  BPM_MAX: 140,
  BPM_DEFAULT: 60,

  // Hit Windows (ms)
  WINDOW_PERFECT: 100,
  WINDOW_GOOD: 200,

  // Calibration
  CALIBRATION_TAP_COUNT: 10,
  CALIBRATION_MIN_INTERVAL: 300,
  CALIBRATION_MAX_INTERVAL: 2000,

  // Adaptation
  PERFECT_RATE_THRESHOLD: 0.85,
  MISS_RATE_THRESHOLD: 0.25,
  BPM_INCREMENT: 3,
  BPM_DECREMENT: 5,
  BPM_ADJUSTMENT_MAX: 20,
  EVALUATION_WINDOW_SIZE: 20,
  EVALUATION_WINDOW_TIME: 20000,

  // Slowdown
  SLOWDOWN_FACTOR: 0.75,
  SLOWDOWN_MISS_THRESHOLD: 0.30,
  SLOWDOWN_CHECK_WINDOW: 10,
  SLOWDOWN_TRANSITION_TIME: 500,

  // Session
  DEFAULT_SESSION_DURATION: 300,
  SESSION_WARNING_TIME: 30,

  // Input
  MIN_TAP_INTERVAL: 100,
};
